$uwsm = uwsm app --
 
$terminal = $uwsm kitty
$fileManager = $uwsm thunar
# $menu = $uwsm wofi --show drun
$menu = rofi -show drun
$search = $uwsm /home/br0wnie/.config/scripts/fuzzel_search
$bar_menu = $uwsm nwg-bar
$browser = $uwsm zen
$screenshot = $uwsm grimblast --freeze copy area -- | swappy -
$emoji_picker = $uwsm wofi-emoji
$color_picker = $uwsm hyprpicker | wl-copy
$calc = $uwsm /home/br0wnie/.config/scripts/fuzzel_calc
$find = $uwsm /home/br0wnie/.config/scripts/fuzzel_find
