$uwsm = uwsm app --
 
$terminal = $uwsm kitty
$fileManager = $uwsm thunar
$menu = rofi -show drun
$search = $uwsm /home/br0wnie/.config/scripts/rofi_search
$bar_menu = $uwsm nwg-bar
$browser = $uwsm zen
$screenshot = $uwsm grimblast --freeze copy area -- | swappy -
$color_picker = $uwsm hyprpicker | wl-copy
