$app_uwsm_launcher = uwsm app --
 
$terminal = $app_uwsm_launcher kitty
$fileManager = $app_uwsm_launcher thunar
$menu = $app_uwsm_launcher wofi --show drun
$bar_menu = $app_uwsm_launcher nwg-bar
$browser = $app_uwsm_launcher thorium-browser
$screenshot = $app_uwsm_launcher grim -g "$(slurp)" - | swappy -f -
