
$uwsm_app_launcher = uwsm app --

exec-once = hyprctl setcursor Bibata-Modern-Ice 24
# exec-once = $uwsm_app_launcher $HOME/.config/hypr/scripts/fullscreen_video_handler.sh
exec-once = $uwsm_app_launcher udiskie
exec-once = $uwsm_app_launcher swayosd-server 

# exec-once = $uwsm_app_launcher hyprpanel 
exec-once = $uwsm_app_launcher waybar 

exec-once = $uwsm_app_launcher wl-paste --type text --watch cliphist store
exec-once = $uwsm_app_launcher wl-paste --type image --watch cliphist store 

