exec-once = $uwsm_app_launcher hyprpaper 
exec-once = $uwsm_app_launcher mako
exec-once = hyprctl setcursor Bibata-Modern-Ice 24
exec-once = $uwsm_app_launcher $HOME/.config/hypr/scripts/fullscreen_video_handler.sh

