$app = uwsm app --

exec-once = hyprctl setcursor Bibata-Modern-Ice 24
# exec-once = $app $HOME/.config/hypr/scripts/fullscreen_video_handler.sh
exec-once = $app udiskie
exec-once = $app swayosd-server 

# exec-once = $app hyprpanel 
# exec-once = $app waybar 

exec-once = $app wl-paste --type text --watch cliphist store
exec-once = $app wl-paste --type image --watch cliphist store 

# exec-once= $app walker --gapplication-service
