# preload = /home/$USER/.wallpaper/retro-poster-planet.png
# wallpaper =, /home/$USER/.wallpaper/retro-poster-planet.png

preload = /home/$USER/Pictures/wallpaper_pspgo_no_table.png
wallpaper =, /home/$USER/Pictures/wallpaper_pspgo_no_table.png

