$mainMod = SUPER

monitor= DP-1, 2560x1440@180, 1920x0, auto, bitdepth, 10, cm, auto, vrr, 2
monitor = DP-2, 1920x1080@144, 0x0, auto

source = $HOME/.config/hypr/apps.conf
source = $HOME/.config/hypr/autostart.conf
source = $HOME/.config/hypr/env.conf
source = $HOME/.config/hypr/look.conf
source = $HOME/.config/hypr/input.conf
source = $HOME/.config/hypr/keybinds.conf
source = $HOME/.config/hypr/rules.conf
